### PR TITLE
Added the findOrFail() and getKey() methods to the HasCompositePrimaryKey Trait

### PR DESCRIPTION
**Pull request by nd9600**
I wasn't able to call the `refresh()` method on any on my Eloquent models, so I added this method to let me do so.

### CODE REVIEW

**Comment by mopo922** [comment]
Thank you! I'm wondering if we should add overrides for `findOrFail()` and `getKey()` instead. That might provide more useful functionality to a broader audience, and it reduces the number of places we have to `foreach` over the keys.

Let's explore that approach before deciding whether or not to merge this.

**Comment by nd9600** [comment]
I've added overrides for `findOrFail()` and `getKey()`, now, rather than `refresh()`.

**Comment by nd9600** [comment]
Did you take a look at the recent changes @mopo922?

**Comment by mopo922** [comment]
Hi @nd9600 - I'm so sorry for leaving you hanging.

I finally had a chance to look at this, and I wasn't sold on the new commit either. I did, however, push a fix to `master` here that should add support for `refresh()`.

Thanks for bringing this to my attention, and again - sorry for the delay.

**Pull request closed without merging**
